import { useCallback, useState } from "react";
import { AlertTriangle, ChevronDown, Clipboard, FileImage, Info, LoaderCircle, LockKeyhole, RotateCcw, ShieldCheck, Sparkles, UploadCloud } from "lucide-react";
import { createC2pa } from "@contentauth/c2pa-web/inline";
import exifr from "exifr";
import Mentoring from "./Mentoring";
import "./checker.css";

type Level = "explicit" | "possible" | "none_detected";
type Finding = { key: string; value: string; source: string; level: Level };
type ScanResult = { file: File; level: Level; findings: Finding[]; c2pa: boolean; error?: string };

const AI_TERMS = ["containsaigeneratedcontent", "trainedalgorithmicmedia", "compositewithtrainedalgorithmicmedia", "generative ai", "content credentials", "canva ai", "adobe firefly", "openai", "chatgpt", "dall-e", "gemini", "midjourney", "stable diffusion"];
const SOURCE_LABELS: Record<string, string> = { trainedAlgorithmicMedia: "생성형 AI로 제작된 콘텐츠", compositeWithTrainedAlgorithmicMedia: "생성형 AI 미디어가 포함된 합성 콘텐츠", algorithmicallyEnhanced: "알고리즘으로 수정된 콘텐츠" };

function naturalSort(files: File[]) { return [...files].sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true, sensitivity: "base" })); }
function flatten(value: unknown, path = "", output: Finding[] = []) { if (!value || typeof value !== "object") return output; Object.entries(value as Record<string, unknown>).forEach(([key, item]) => { const next = path ? `${path}.${key}` : key; if (item && typeof item === "object") flatten(item, next, output); else if (item !== undefined && item !== null) output.push({ key: next, value: String(item), source: "metadata", level: "possible" }); }); return output; }
async function scanFile(file: File): Promise<ScanResult> {
  const findings: Finding[] = []; let raw = ""; let hasC2pa = false;
  try { raw = new TextDecoder("latin1").decode(await file.arrayBuffer()); } catch { /* continue with other readers */ }
  const lower = raw.toLowerCase();
  if (lower.includes("cabx")) findings.push({ key: "PNG caBX", value: "발견됨", source: "png_chunk", level: "possible" });
  AI_TERMS.forEach(term => { if (lower.includes(term)) findings.push({ key: "Raw metadata string", value: term, source: "raw_string", level: term.includes("trained") || term.includes("containsai") ? "explicit" : "possible" }); });
  try { const metadata = await exifr.parse(file, { xmp: true, iptc: true, exif: true, tiff: true, jfif: true }); flatten(metadata).forEach(item => { const haystack = `${item.key} ${item.value}`.toLowerCase(); if (haystack.includes("containsaigeneratedcontent") || haystack.includes("trainedalgorithmicmedia") || haystack.includes("generative ai") || haystack.includes("firefly") || haystack.includes("canva ai") || haystack.includes("openai")) findings.push({ ...item, source: "xmp/exif", level: "explicit" }); }); } catch { /* unsupported metadata is not a total failure */ }
  try { const sdk = await createC2pa(); const reader = await sdk.reader.fromBlob(file.type, file); if (reader) { hasC2pa = true; flatten(await reader.manifestStore()).forEach(item => { const haystack = `${item.key} ${item.value}`.toLowerCase(); if (haystack.includes("trainedalgorithmicmedia") || haystack.includes("generative") || haystack.includes("containsaigeneratedcontent") || haystack.includes("firefly") || haystack.includes("canva ai") || haystack.includes("openai")) findings.push({ ...item, source: "c2pa", level: "explicit" }); }); await reader.free(); } } catch { /* C2PA is absent or unreadable */ }
  const unique = findings.filter((item, index, all) => all.findIndex(other => other.key === item.key && other.value === item.value) === index);
  const explicit = unique.some(item => item.level === "explicit") || /containsaigeneratedcontent.{0,30}(yes|true)|trainedalgorithmicmedia|compositewithtrainedalgorithmicmedia/i.test(raw);
  return { file, level: explicit ? "explicit" : unique.length ? "possible" : "none_detected", findings: unique, c2pa: hasC2pa };
}

function LevelBadge({ level }: { level: Level }) { return <span className={`level-badge ${level}`}><i />{level === "explicit" ? "명시적 신호" : level === "possible" ? "확인 필요" : "발견되지 않음"}</span>; }
function Checker() {
  const [results, setResults] = useState<ScanResult[]>([]); const [expanded, setExpanded] = useState<number[]>([]); const [busy, setBusy] = useState(false); const [dragging, setDragging] = useState(false); const [copied, setCopied] = useState(false); const [toast, setToast] = useState(false);
  const analyze = useCallback(async (input: FileList | File[]) => { const files = naturalSort(Array.from(input).filter(file => /image\/(png|jpe?g|webp)/.test(file.type) || /\.(png|jpe?g|webp)$/i.test(file.name))); if (!files.length) return; setBusy(true); setResults([]); setExpanded([]); for (const file of files) { const item = await scanFile(file); setResults(current => [...current, item]); setExpanded(current => item.level !== "none_detected" ? [...current, current.length] : current); } setBusy(false); setToast(true); window.setTimeout(() => setToast(false), 3600); window.setTimeout(() => document.getElementById("scan-results")?.scrollIntoView({ behavior: "smooth", block: "start" }), 120); }, []);
  const summary = { explicit: results.filter(item => item.level === "explicit").length, possible: results.filter(item => item.level === "possible").length, none: results.filter(item => item.level === "none_detected").length };
  const detectedPages = results.map((item, index) => item.level !== "none_detected" ? index + 1 : null).filter((page): page is number => page !== null);
  const pageText = detectedPages.length > 1 ? `${detectedPages.slice(0, -1).join(", ")} 및 ${detectedPages[detectedPages.length - 1]}페이지` : detectedPages.length === 1 ? `${detectedPages[0]}페이지` : "없음";
  const resultTone = summary.explicit > 0 ? "explicit" : summary.possible > 0 ? "possible" : "none";
  const resultMessage = summary.explicit > 0 ? `${pageText}에서 명시적인 AI 관련 정보가 발견되었습니다.` : summary.possible > 0 ? `${pageText}에서 AI와 관련될 수 있는 정보가 발견되었습니다.` : "검사 가능한 AI 관련 정보가 발견되지 않았습니다.";
  const report = `AI 관련 메타데이터 검사 결과\n총 ${results.length}페이지\n명시적인 AI 관련 정보: ${summary.explicit}페이지\n확인이 필요한 정보: ${summary.possible}페이지\n현재 검사 가능한 AI 관련 정보 없음: ${summary.none}페이지\n\n※ 이 검사에서 AI 관련 정보가 발견되지 않아도 Instagram에서 다른 이유로 AI 정보 라벨이 붙을 수 있습니다.`;
  return <div className="checker-app"><header className="checker-header"><a className="checker-brand" href="/checker"><span className="brand-spark"><Sparkles size={16} /></span>AI Label <b>Checker</b></a><span className="local-pill"><LockKeyhole size={14} /> 파일은 브라우저 안에서만 검사</span></header><main className="checker-main">
    <section className="checker-hero"><div className="checker-mascot"><img src={`${import.meta.env.BASE_URL}assets/kkumuljji/challenge.png`} alt="도전하는 꾸물찌" /><span>CHECK<br />THE FILE</span></div><div><p className="checker-kicker">AI PROVENANCE / PREFLIGHT</p><h1>Instagram에 올리기 전에<br /><em>파일 속 정보를 확인하세요.</em></h1><p className="checker-lead">AI 이미지 판별기가 아닙니다.<br />파일 안에서 확인할 수 있는 C2PA, XMP와 AI 관련 metadata를 검사합니다.</p></div><div className="hero-signal"><span className="signal-dot" /><span className="signal-dot" /><span className="signal-dot" /><strong>NOT AN<br />AI DETECTOR</strong></div></section>
    <section className={`drop-zone ${dragging ? "is-dragging" : ""}`} onDragOver={event => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={event => { event.preventDefault(); setDragging(false); void analyze(event.dataTransfer.files); }}><UploadCloud size={34} /><h2>이미지를 끌어놓거나 선택하기</h2><p>PNG · JPG · JPEG · WEBP &nbsp; · &nbsp; 여러 장을 한 번에 검사할 수 있습니다.</p><label className="file-button">파일 선택<input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={event => { if (event.target.files) void analyze(event.target.files); }} /></label>{busy && <div className="progress"><LoaderCircle size={16} /> {results.length}개 검사 중...</div>}</section>
    <section className="critical-warning"><AlertTriangle size={22} /><div><strong>꼭 확인해주세요</strong><p>여기에서 AI 관련 정보가 발견되지 않아도 <b>Instagram에서 AI 정보 라벨이 붙을 수 있습니다.</b></p><small>Instagram은 파일 metadata 외의 다른 신호나 자체 탐지 시스템을 사용할 수 있습니다.</small></div></section>{results.length > 0 && <a className="results-anchor" href="#scan-results"><span><Sparkles size={15} /> 검사 완료 · 아래에서 결과를 확인하세요</span><ChevronDown size={16} /></a>}
    {results.length > 0 && <section className="results-section" id="scan-results"><div className={`result-summary-banner ${resultTone}`}><span className="result-summary-icon"><Sparkles size={17} /></span><strong>{resultMessage}</strong></div><div className="results-head"><div><p className="checker-kicker">SCAN RESULT</p><h2>검사 완료 <span>{results.length}페이지</span></h2></div><button className="ghost-button" onClick={() => setResults([])}><RotateCcw size={15} /> 새로 검사</button></div><div className="summary-grid"><div><span className="summary-number">{summary.explicit}</span><span><i className="red-dot" />명시적인 AI 관련 정보</span></div><div><span className="summary-number">{summary.possible}</span><span><i className="orange-dot" />확인이 필요한 정보</span></div><div><span className="summary-number">{summary.none}</span><span><i className="green-dot" />현재 검사 가능한 정보 없음</span></div></div><div className="result-list">{results.map((result, index) => <article className="result-card" key={`${result.file.name}-${index}`}><button className="result-main" onClick={() => setExpanded(expanded.includes(index) ? expanded.filter(item => item !== index) : [...expanded, index])} aria-expanded={expanded.includes(index)}><span className="page-no">{String(index + 1).padStart(2, "0")}</span><span className="result-file"><FileImage size={17} /><b>{result.file.name}</b><small>{Math.round(result.file.size / 1024)} KB</small></span><LevelBadge level={result.level} /><ChevronDown className={expanded.includes(index) ? "rotate" : ""} size={18} /></button>{expanded.includes(index) && <div className="details"><p className="detail-title">{result.level === "explicit" ? "명시적인 AI 관련 정보가 확인되었습니다." : result.level === "possible" ? "AI와 관련될 수 있는 정보가 발견되었습니다." : "현재 검사 가능한 AI 관련 정보가 발견되지 않았습니다."}</p>{result.findings.length ? <div className="finding-list">{result.findings.map((finding, findingIndex) => <div className="finding" key={`${finding.key}-${findingIndex}`}><span>{finding.source}</span><b>{finding.key}</b><code>{SOURCE_LABELS[finding.value] || finding.value}</code></div>)}</div> : <p className="muted">C2PA, XMP, IPTC/EXIF, PNG chunk 및 보조 문자열에서 관련 신호가 확인되지 않았습니다.</p>}<p className="trace-hint"><Info size={16} /> 원인을 좁히고 싶다면 원본 편집 프로그램에서 해당 페이지를 복제하고, 의심되는 요소를 하나 제외해 다시 export한 뒤 재검사해보세요. 검사기 안에서 이미지를 직접 수정하지 마세요.</p></div>}</article>)}</div><div className="result-warning"><AlertTriangle size={18} /><span><b>Instagram 라벨 여부를 보장하지 않습니다.</b><br />이 검사에서 아무것도 발견되지 않은 이미지도 Instagram에서 다른 이유로 AI 정보 라벨이 붙을 수 있습니다.</span></div><button className="copy-report" onClick={() => { void navigator.clipboard.writeText(report); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }}><Clipboard size={16} />{copied ? "결과가 복사되었습니다" : "결과 복사"}</button></section>}
    <section className="how-section"><div className="how-mascot"><img src={`${import.meta.env.BASE_URL}assets/kkumuljji/study.png`} alt="공부하는 꾸물찌" /></div><div><p className="checker-kicker">HOW TO READ</p><h2>이 도구가 말해주는 것</h2></div><div className="how-grid"><div><span>01</span><h3>파일 안의 출처 정보</h3><p>C2PA가 있다고 해서 AI라는 뜻은 아닙니다. manifest 안의 assertion과 source type을 함께 살핍니다.</p></div><div><span>02</span><h3>vendor-neutral 검사</h3><p>Canva는 가능한 출처 중 하나일 뿐입니다. 다양한 provider와 알 수 없는 출처도 확인합니다.</p></div><div><span>03</span><h3>로컬 분석</h3><p>이미지는 서버로 전송되지 않습니다. 선택한 파일은 현재 브라우저 안에서만 처리됩니다.</p></div></div></section>
    </main><footer className="checker-footer"><span>AI Label Checker</span><span>파일 내부의 provenance만 검사합니다.</span></footer><div className={`scan-toast ${toast ? "show" : ""}`} role="status"><Sparkles size={16} /> 검사 완료했어요. 아래 결과를 확인해주세요.</div></div>;
}
export default function App() { return window.location.pathname.endsWith("/checker") || window.location.hash === "#/checker" ? <Checker /> : <Mentoring />; }
