import { useState } from "react";
import { ArrowDown, ArrowUpRight, Check, Clock3, Copy, Mail, MessageCircle, ShieldCheck, Sparkles, Trophy } from "lucide-react";

const FORM_URL = "https://naver.me/FbV7OHL5";

function Label({ children }: { children: React.ReactNode }) { return <p className="section-label">{children}</p>; }
function Notice({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return <article className="notice-card"><span className="notice-number">{number}</span><div><h3>{title}</h3><div className="notice-copy">{children}</div></div></article>;
}
function ContactCard({ type, label, value }: { type: "chat" | "email"; label: string; value: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => { await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1600); };
  return <div className={`contact-card ${type}`}><span className="contact-icon">{type === "chat" ? <MessageCircle size={22} /> : <Mail size={22} />}</span><div className="contact-value"><small>{label}</small><strong>{value}</strong></div><button className="copy-button" onClick={copy} aria-label={`${value} 복사`}><Copy size={15} />{copied ? "복사됨" : "복사"}</button></div>;
}

export default function App() {
  return <div className="site-shell">
    <header className="site-header"><a className="wordmark" href="#top"><span className="wordmark-dot" /> 꾸물찌팀</a><nav className="desktop-nav"><a href="#start">시작하기</a><a href="#notices">공지 모아보기</a><a href="#contact">문의하기</a></nav><a className="header-cta" href={FORM_URL} target="_blank" rel="noreferrer">사전 질문지 <ArrowUpRight size={15} /></a></header>
    <main id="top">
      <section className="hero" aria-labelledby="hero-title"><div className="hero-glow glow-one" /><div className="hero-glow glow-two" /><div className="hero-copy"><p className="eyebrow"><Sparkles size={15} /> 한 달 집중 멘토링</p><h1 id="hero-title">우리 같이<br /><em>해보자!</em></h1><p className="hero-description">한 달 동안 콘텐츠 5개,<br className="desktop-only" /> 아자자!</p><div className="hero-actions"><a className="button button-primary" href={FORM_URL} target="_blank" rel="noreferrer">사전 질문지 작성하기 <ArrowUpRight size={18} /></a><a className="text-link" href="#start">진행 방식 보기 <ArrowDown size={16} /></a></div></div><div className="hero-art" aria-label="도전하는 꾸물찌 캐릭터"><div className="art-sticker">REFERENCE<br />→ HYPOTHESIS</div><img src={`${import.meta.env.BASE_URL}assets/kkumuljji/challenge.png`} alt="도전하는 꾸물찌" /><div className="art-note"><span>01</span>작은 실험이<br />큰 변화를 만들어요</div></div></section>
      <section className="quick-start section" id="start"><div className="section-intro"><Label>START HERE</Label><h2>처음 오셨다면<br /><strong>이 순서대로</strong> 읽어주세요.</h2><p>공지와 안내가 많아도 괜찮아요. 지금 필요한 내용부터 차근차근 확인하면 됩니다.</p></div><div className="step-grid"><div className="step-card step-card-featured"><span>01</span><strong>사전 질문지 작성</strong><p>계정의 현재 모습과 목표를 알려주세요.</p><img src={`${import.meta.env.BASE_URL}assets/kkumuljji/idea.png`} alt="생각하는 꾸물찌" /></div><div className="step-card"><span>02</span><strong>계정 방향 잡기</strong><p>레퍼런스를 함께 살펴보고 정체성을 정해요.</p></div><div className="step-card"><span>03</span><strong>콘텐츠 5개 실행</strong><p>만들고, 올리고, 데이터를 확인합니다.</p></div></div></section>
      <section className="goal-banner section"><div className="goal-image"><img src={`${import.meta.env.BASE_URL}assets/kkumuljji/go.png`} alt="해보자고 응원하는 꾸물찌" /></div><div><Label>OUR ONE-MONTH GOAL</Label><h2>콘텐츠랩과 별개로<br /><strong>게시물 5개 만들기</strong></h2><p>완성한 콘텐츠는 2~3일 안에 모아서 업로드합니다. 직접 올리고 데이터로 확인하는 것이 목표예요.</p></div><div className="goal-badge"><span>5</span><small>POSTS<br />TO GO</small></div></section>
      <section className="section notice-section" id="notices"><div className="section-heading-row"><div><Label>NOTICE ARCHIVE</Label><h2>공지 모아보기</h2></div><span className="archive-note">공식 공지부터 읽어주세요</span></div><div className="notice-stack">
        <Notice number="01" title="멘토방 운영 규칙"><p>이 방은 알고리즘을 이해하고 실제 계정 성장으로 연결하기 위한 멘토링방입니다. 목표는 급성장이고, 이를 위해 반드시 레퍼런스를 찾고 가설을 세우고 실험하고 검증합니다.</p><h4>질문은 이 방에 남겨주세요</h4><p>콘텐츠·계정 운영·알고리즘에 관한 질문은 담당 멘토 또는 운영진이 답변드립니다. 개인 메시지는 받지 않으니 꼭 이 방에 질문해 주세요.</p><h4>5기 콘텐츠랩 관련 질문이라면 배경을 자세히 알려주세요</h4><p>제가 5기 콘텐츠랩의 모든 과정을 알고 있는 것은 아닙니다. 콘텐츠랩 관련 질문을 주실 때에는 과제 내용과 현재 상황, 고민하는 지점을 함께 설명해 주세요.</p><div className="notice-example"><strong>예시</strong><br />“00일 과제가 ○○인데, 제 계정 상황은 ○○입니다. 그래서 △△ 방향으로 진행하려고 하는데 어떻게 생각하시나요?”</div><h4>멘토링에서 함께 다루는 것</h4><ul><li>조회수가 잘 나온 콘텐츠의 공통점 분석</li><li>제목·첫 페이지·마지막 페이지 개선</li><li>계정 인사이트와 도달 데이터 분석</li><li>업로드 후 반응에 따른 다음 콘텐츠 방향 설정</li><li>알고리즘을 타기 위한 다양한 콘텐츠 실험</li><li>팔로워 전환율을 높이는 계정 운영 방법</li></ul><div className="notice-callout"><strong>알고리즘에는 하나의 정답이 없습니다.</strong><br />계정마다 알고리즘이 다르기 때문에, 멘토는 가설을 세울 수 있지만 직접 업로드하기 전까지 검증할 수는 없습니다. 답은 여러분이 올리고 데이터를 확인한 뒤에야 알 수 있어요. 변수를 바꿔 여러 번 실험해 주세요.</div><h4>질문할 때 꼭 함께 적어주세요</h4><ul><li>콘텐츠 또는 계정 링크</li><li>콘텐츠의 주제와 의도</li><li>현재 조회수·도달·좋아요·공유·저장 등 주요 인사이트 수치</li><li>본인이 분석한 문제점과 구체적으로 궁금한 부분</li></ul><p>“왜 조회수가 안 나오나요?”보다 자신의 분석과 가설을 함께 남겨주시면 더 깊이 있는 답변을 받을 수 있습니다. 피드백은 반드시 실행으로 연결하고, 적용 후 어떤 변화가 있었는지 공유해 주세요.</p><h4>함께 지켜주세요</h4><ul><li>답변은 질문이 몰릴 경우 순차적으로 진행되며 시간이 걸릴 수 있습니다.</li><li>운영·결제 문의는 머니루트 채널로 연락해 주세요.</li><li>방 안의 계정 데이터·콘텐츠·피드백·사례를 외부에 공유하거나 무단 활용하지 마세요.</li><li>비난·조롱·과도한 홍보·무단 개인 연락 없이 서로의 실험과 성장을 응원해 주세요.</li></ul></Notice>
        <Notice number="02" title="꾸물찌 멘토링 진행 방식"><p>한 달 동안 콘텐츠랩과 별개로 게시물 5개를 제작하고, 완성된 콘텐츠를 2~3일 안에 모아서 업로드하는 것을 목표로 합니다.</p><div className="timeline"><span><b>01</b> 사전 설문</span><span><b>02</b> 정체성 파악</span><span><b>03</b> 방향 피드백</span><span><b>04</b> 5개 제작</span><span><b>05</b> 업로드·분석</span></div><h4>진행 순서</h4><ol><li>사전 설문폼으로 계정의 정체성과 목적을 파악합니다.</li><li>목적에 맞게 계정 정체성에 대한 피드백을 드립니다.</li><li>선택한 특징툰 주제에서 팔로워를 잘 모은 계정들을 분석하고 벤치마킹합니다.</li><li>계정 정체성이 잡히면 5개의 게시물을 만들고 업로드 일자를 정합니다.</li><li>업로드 후 반응과 데이터를 보며 다음 실험 방향을 함께 고민합니다.</li></ol><p className="small-note"><Clock3 size={15} /> 메일 답장은 기본 24시간 이내입니다. 답변의 완성도를 위해 필요한 경우 하루 정도 더 걸릴 수 있습니다.</p><p className="small-note"><ShieldCheck size={15} /> 메일 내용이 전체에 도움이 된다고 판단되면 개인적인 내용은 가리고 원론적인 내용으로 멘토링방에 공유될 수 있습니다.</p></Notice>
        <Notice number="03" title="피드백을 만나는 방법"><p>멘토링 과정에서 만화제면소 측의 피드백과 꾸물찌의 피드백이 함께 제공될 수 있습니다. 저는 만화제면소 쪽에서 어떤 피드백을 드리는지 알 수 없기 때문에, 두 의견이 서로 다를 수 있습니다.</p><div className="notice-callout"><strong>두 피드백 중 하나가 항상 정답인 것은 아닙니다.</strong><br />어떤 방향이 자신의 계정과 목표에 더 맞는지 멘티 여러분이 주관을 가지고 판단해 주세요. “두 피드백이 다른데 어떻게 해야 하나요?”라고 다시 질문해 주셔도 괜찮습니다. 그 답변을 바탕으로 한 최종 판단 역시 여러분의 몫입니다.</div><div className="feature-chips"><span>계정 방향</span><span>제목·첫 페이지·마지막 페이지</span><span>인사이트 분석</span><span>다음 콘텐츠 전략</span></div></Notice>
        <Notice number="04" title="조별 챌린지 안내"><p>8월 30일까지 업로드된 콘텐츠 성과를 기준으로 조장을 선정합니다. 조장님은 운영자와 1:1 미팅을 진행하고, 멘토님과 함께 조원들의 성장을 돕게 됩니다.</p><div className="event-callout"><Trophy size={20} /><span>챌린지 기간 동안 조원 평균 팔로워 수가 가장 높은 조에는 별도 상품이 제공됩니다. 레퍼런스와 인사이트를 나누며 함께 성장해요.</span></div></Notice>
      </div></section>
      <section className="principles section"><div className="principles-art"><img src={`${import.meta.env.BASE_URL}assets/kkumuljji/study.png`} alt="공부하는 꾸물찌" /></div><div><Label>KKUMULJJI'S NOTE</Label><h2>인스타툰 철칙은<br /><strong>곧 업데이트할게요.</strong></h2><p>멘토링하는 동안 계속 꺼내 보게 될 핵심 원칙과 체크리스트를 이곳에 모아둘 예정입니다.</p><div className="coming-soon"><Check size={17} /> 오늘의 실행을 내일의 데이터로</div></div></section>
      <section className="contact section" id="contact"><div className="contact-copy"><Label>CONTACT</Label><h2>궁금한 건<br /><strong>아무 때나 물어보세요.</strong></h2><p>짧은 질문도, 길고 복잡한 고민도 괜찮아요. 질문의 성격에 맞는 채널을 골라주세요.</p></div><div className="contact-cards"><ContactCard type="chat" label="바로바로 답변받고 싶을 때" value="[특징툰] 꾸물찌팀 오픈 채팅방" /><ContactCard type="email" label="길고 복잡한 내용·콘텐츠 피드백" value="solppulia@gmail.com" /></div></section>
    </main><footer><span>꾸물찌팀 × 인스타툰 멘토링</span><span>실험하고, 올리고, 함께 분석해요.</span></footer><a className="floating-form" href={FORM_URL} target="_blank" rel="noreferrer">사전 질문지 <ArrowUpRight size={16} /></a>
  </div>;
}
